// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVR0aolbJpGupIaWqA198V_5B3SsVKxrA',
    appId: '1:288169206758:web:29187aacfb09c31cbd2c27',
    messagingSenderId: '288169206758',
    projectId: 'fir-course-6bb48',
    authDomain: 'fir-course-6bb48.firebaseapp.com',
    storageBucket: 'fir-course-6bb48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZuiNcwbHsr9Zait2X-GPLUOtYCrbTMow',
    appId: '1:288169206758:android:9a00d66046d4ef33bd2c27',
    messagingSenderId: '288169206758',
    projectId: 'fir-course-6bb48',
    storageBucket: 'fir-course-6bb48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKsWZ9gxMd-KoLqdn6CU6FwRj7P1OUSs8',
    appId: '1:288169206758:ios:d6528daa764d9dd6bd2c27',
    messagingSenderId: '288169206758',
    projectId: 'fir-course-6bb48',
    storageBucket: 'fir-course-6bb48.firebasestorage.app',
    iosBundleId: 'com.example.firebasecourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKsWZ9gxMd-KoLqdn6CU6FwRj7P1OUSs8',
    appId: '1:288169206758:ios:d6528daa764d9dd6bd2c27',
    messagingSenderId: '288169206758',
    projectId: 'fir-course-6bb48',
    storageBucket: 'fir-course-6bb48.firebasestorage.app',
    iosBundleId: 'com.example.firebasecourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVR0aolbJpGupIaWqA198V_5B3SsVKxrA',
    appId: '1:288169206758:web:a7eaef4964c22920bd2c27',
    messagingSenderId: '288169206758',
    projectId: 'fir-course-6bb48',
    authDomain: 'fir-course-6bb48.firebaseapp.com',
    storageBucket: 'fir-course-6bb48.firebasestorage.app',
  );
}
